### ISSUE TITLE
Dark Mode Changing Colours 

### ISSUE THREAD

**Issue by ady1984** [hteumeuleu/email-bugs#85] opened 2020-09-23 06:49 UTC
Dark Mode is causing the blue to change colour, this makes the email look strange when there is a image below with the correct brand image - also the blue is changing on the buttons making them hard to read as there is dark text on a dark button 

![DarkMode](https://user-images.githubusercontent.com/71751482/93976631-eacaf700-fd81-11ea-8ccb-8768bfa97f3b.jpg)

![IMG_2421 (1)](https://user-images.githubusercontent.com/71751482/93976508-c242fd00-fd81-11ea-91db-671e039c7f02.PNG)

**Comment by hteumeuleu** [comment] 2020-09-23 08:03
This is Gmail Android, right? If so, can you [post here](https://github.com/hteumeuleu/email-bugs/issues/68) as it looks like a duplicate of #68.

**Comment by hteumeuleu** [comment] 2020-10-27 20:00
I'm closing this as it's a duplicate. Feel free to contribute to the other issue if you want.

**Closed by hteumeuleu** 2020-10-27 20:00 UTC
Labels: Gmail
